### ISSUE TITLE
Question about _id inserting in Raw mode

### ISSUE THREAD

**Issue by thiyaga123** [hiddentao/robe#7]
Hi 
 When i insert document with my own _id field and value  _id = "ABCDED";  
i am getting below error. please let me knonw how to pass 
i want to insert my own mongodb _id field. please let me know how to do that.

Error: Argument passed in must be a single String of 12 bytes or a string of 24
hex characters
    at new ObjectID (Path\\node_modules
\robe\node_modules\monk\node_modules\mongoskin\node_modules\mongodb\node_modules
\bson\lib\bson\objectid.js:35:11)
    at SkinClass.ObjectID [as id] (
p\node_modules\robe\node_modules\monk\node_modules\mongoskin\node_modules\mongod
b\node_modules\bson\lib\bson\objectid.js:26:42)
    at Collection.id.Collection.oid (node_modules\robe\node_modules\monk\lib\collection.js:51:44)
    at Collection.cast (Path\\node_modu
les\robe\node_modules\monk\lib\collection.js:532:20)
    at Collection.insert (Path\\node_mo
dules\robe\node_modules\monk\lib\collection.js:316:15)
    at Collection.insert (Path\\node_mo
dules\robe\build\collection.js:162:41)
    at GeneratorFunctionPrototype.next (native)
    at onFulfilled (Path\\node_modules\
co\index.js:64:19)
    at runMicrotasksCallback (node.js:337:7)
    at process._tickCallback (node.js:355:11)

**Comment by hiddentao** [comment]
This seems to be a problem in Monk (see https://github.com/Automattic/monk/issues/1). It needs to be fixed there for it to work in Robe. In future I may remove Monk and directly call through to the native node.js layer but for now we're stuck with this issue until it gets fixed in Monk.

**Comment by mathieudutour** [comment]
This is now fixed in monk
